language: go
go: "1.10"

before_install:
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/mattn/goveralls

install:
  - go get github.com/Sirupsen/logrus
  - go get github.com/kelseyhightower/envconfig

script:
  - $HOME/gopath/bin/goveralls -service=travis-ci
  - make test
